In [1]:
import csv
import pandas as pd

In [2]:
df_area = pd.read_csv("data.csv")

C:\Users\rbors\AppData\Local\Temp\ipykernel_9364\3038614085.py:1: DtypeWarning: Columns (2,11,12,14,15,16,17,19,20,21,22,23,24,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df_area = pd.read_csv("data.csv")

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
df_area['boroughs'] = df_area['LSOA name'].apply(lambda x: x.split(' ')[0] if pd.notnull(x) else x)

In [23]:
df_area2 = df_area[df_area['Type'].notnull()]
df_search = df_area2[['Longitude', 'Latitude', 'Type', 'Date', 'Gender', 'Age range', 'Self-defined ethnicity', 'Officer-defined ethnicity', 'Object of search', 'Outcome']]
df_search[df_search['Longitude'].notnull()].to_csv('Search.csv')

In [4]:
boroughs_list = [
    "Barking and Dagenham",
    "Barnet",
    "Bexley",
    "Brent",
    "Bromley",
    "Camden",
    "Croydon",
    "Ealing",
    "Enfield",
    "Greenwich",
    "Hackney",
    "Hammersmith and Fulham",
    "Haringey",
    "Harrow",
    "Havering",
    "Hillingdon",
    "Hounslow",
    "Islington",
    "Kensington and Chelsea",
    "Kingston upon Thames",
    "Lambeth",
    "Lewisham",
    "Merton",
    "Newham",
    "Redbridge",
    "Richmond upon Thames",
    "Southwark",
    "Sutton",
    "Tower Hamlets",
    "Waltham Forest",
    "Wandsworth",
    "Westminster"]

In [5]:
def check_borough(lsoa_name, boroughs_list):
    for borough in boroughs_list:
        if borough in lsoa_name:
            return borough
    return None

df_area['boroughs'] = df_area['LSOA name'].apply(lambda x: check_borough(x, boroughs_list) if pd.notnull(x) else x)

In [10]:
df_crimes = df_area[df_area['boroughs'].notna()]

In [14]:
df_crimes

,Unnamed: 0.1,Unnamed: 0,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context,Outcome type,Type,Date,Part of a policing operation,Policing operation,Gender,Age range,Self-defined ethnicity,Officer-defined ethnicity,Legislation,Object of search,Outcome,Outcome linked to object of search,Removal of more than just outer clothing,boroughs
0,0,0,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,0.145949,51.593914,On or near Providence Place,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Barking and Dagenham
1,1,1,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,0.140192,51.582311,On or near Hatch Grove,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Barking and Dagenham
2,2,2,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,0.134947,51.588063,On or near Mead Grove,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Barking and Dagenham
3,3,3,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,0.134947,51.588063,On or near Mead Grove,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Barking and Dagenham
4,4,4,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,0.134947,51.588063,On or near Mead Grove,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Barking and Dagenham
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23605977,23605977,191293,cb73daf6b8479ac3c6f0393ccaed8ba09d656bc8ec7daf...,2024-01,Metropolitan Police Service,Metropolitan Police Service,-0.133480,51.486807,On or near St George'S Square Mews,E01035722,Westminster 024G,Criminal damage and arson,Under investigation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Westminster
23605978,23605978,191294,9bf4d909cbf838f713421c29a173c1fd1578393789ce37...,2024-01,Metropolitan Police Service,Metropolitan Police Service,-0.136284,51.485152,On or near Petrol Station,E01035722,Westminster 024G,Other theft,Under investigation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Westminster
23605979,23605979,191295,90ce6cc23afb135dcbc5eb17784b4d363375f9a076a2fd...,2024-01,Metropolitan Police Service,Metropolitan Police Service,-0.136284,51.485152,On or near Petrol Station,E01035722,Westminster 024G,Theft from the person,Investigation complete; no suspect identified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Westminster
23605980,23605980,191296,be7a1b283771dc0aefcef2b191a4f7e91403771e1d6065...,2024-01,Metropolitan Police Service,Metropolitan Police Service,-0.137230,51.486309,On or near Parking Area,E01035722,Westminster 024G,Violence and sexual offences,Under investigation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Westminster
23605981,23605981,191297,9006968a8e2fb5779017e7c6f1887ad21232b565cfe6df...,2024-01,Metropolitan Police Service,Metropolitan Police Service,-0.136284,51.485152,On or near Petrol Station,E01035722,Westminster 024G,Violence and sexual offences,Investigation complete; no suspect identified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Westminster

In [13]:
dataframe = df_crimes[["Crime ID", "Month", "Crime type", "Last outcome category", "boroughs"]]
dataframe

,Crime ID,Month,Crime type,Last outcome category,boroughs
0,NaN,2010-12,Anti-social behaviour,NaN,Barking and Dagenham
1,NaN,2010-12,Anti-social behaviour,NaN,Barking and Dagenham
2,NaN,2010-12,Anti-social behaviour,NaN,Barking and Dagenham
3,NaN,2010-12,Anti-social behaviour,NaN,Barking and Dagenham
4,NaN,2010-12,Anti-social behaviour,NaN,Barking and Dagenham
...,...,...,...,...,...
23605977,cb73daf6b8479ac3c6f0393ccaed8ba09d656bc8ec7daf...,2024-01,Criminal damage and arson,Under investigation,Westminster
23605978,9bf4d909cbf838f713421c29a173c1fd1578393789ce37...,2024-01,Other theft,Under investigation,Westminster
23605979,90ce6cc23afb135dcbc5eb17784b4d363375f9a076a2fd...,2024-01,Theft from the person,Investigation complete; no suspect identified,Westminster
23605980,be7a1b283771dc0aefcef2b191a4f7e91403771e1d6065...,2024-01,Violence and sexual offences,Under investigation,Westminster
23605981,9006968a8e2fb5779017e7c6f1887ad21232b565cfe6df...,2024-01,Violence and sexual offences,Investigation complete; no suspect identified,Westminster

In [18]:
dataframe.to_csv('crimes.csv')

In [19]:
df_search = df_area[df_area['Type'].notnull()]
df_search = df_search[['Longitude', 'Latitude', 'Type', 'Date', 'Gender', 'Age range', 'Self-defined ethnicity', 'Officer-defined ethnicity', 'Object of search', 'Outcome']]
df_search.to_csv('search.csv')