In [2]:
import csv
import pandas as pd
import os
import shutil

In [10]:
dir_path = './sorted_data'
new_root_dir = './sorted_data_2'

for dir_path, dir_names, file_names in os.walk(dir_path):
    for file_name in file_names:
        if file_name.split('-')[2] == 'metropolitan':
            year = dir_path.split("\\")[1].split("-")[0]
            new_dir_path = os.path.join(new_root_dir, year)

            # Create new directory if it doesn't exist
            if not os.path.exists(new_dir_path):
                os.makedirs(new_dir_path)

            old_file_path = os.path.normpath(os.path.join(dir_path, file_name))
            new_file_path = os.path.normpath(os.path.join(new_dir_path, file_name))

            # Move the file to the new directory
            shutil.move(old_file_path, new_file_path)

In [11]:
dir_path = './sorted_data_2'
files = []

subfolders = [ f.path.replace("\\", "/") for f in os.scandir(dir_path) if f.is_dir() ]
for file in subfolders:
    year =  file.split('/')[2]
    print(file)
    dfs = []
    for (dirpath, dirnames, filenames) in os.walk(file):
        for x in filenames:
            df = pd.read_csv(f'{file}//{x}')
            dfs.append(df)
    df = pd.concat(dfs, ignore_index=True)
    df.to_csv(f'{year}.csv')
    print("done")

./sorted_data_2/2010
done
./sorted_data_2/2011
done
./sorted_data_2/2012
done
./sorted_data_2/2013
done
./sorted_data_2/2014
done
./sorted_data_2/2015
done
./sorted_data_2/2016
done
./sorted_data_2/2017
done
./sorted_data_2/2018
done
./sorted_data_2/2019
done
./sorted_data_2/2020
done
./sorted_data_2/2021
done
./sorted_data_2/2022
done
./sorted_data_2/2023
done
./sorted_data_2/2024
done

In [12]:
dfs = []
for (dirpath, dirnames, filenames) in os.walk('./csv_files'):
    for x in filenames:
        df = pd.read_csv(f'./csv_files/{x}')
        dfs.append(df)

C:\Users\rbors\AppData\Local\Temp\ipykernel_18736\4233950251.py:4: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f'./csv_files/{x}')
C:\Users\rbors\AppData\Local\Temp\ipykernel_18736\4233950251.py:4: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f'./csv_files/{x}')
C:\Users\rbors\AppData\Local\Temp\ipykernel_18736\4233950251.py:4: DtypeWarning: Columns (10,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f'./csv_files/{x}')
C:\Users\rbors\AppData\Local\Temp\ipykernel_18736\4233950251.py:4: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f'./csv_files/{x}')
C:\Users\rbors\AppData\Local\Temp\ipykernel_18736\4233950251.py:4: DtypeWarning: Columns (10,11,12,14,15,18,19,20,21,22,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f'./csv_files/{x}')
C:\Users\rbors\AppData\Local\Temp\ipykernel_18736\4233950251.py:4: DtypeWarning: Columns (10,11,12,13,15,16,17,18,19,20,21,24,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f'./csv_files/{x}')
C:\Users\rbors\AppData\Local\Temp\ipykernel_18736\4233950251.py:4: DtypeWarning: Columns (10,11,12,13,15,16,17,18,19,20,21,24,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f'./csv_files/{x}')
C:\Users\rbors\AppData\Local\Temp\ipykernel_18736\4233950251.py:4: DtypeWarning: Columns (8,9,10,11,12,13,15,16,17,18,19,20,21,24,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f'./csv_files/{x}')
C:\Users\rbors\AppData\Local\Temp\ipykernel_18736\4233950251.py:4: DtypeWarning: Columns (10,11,12,13,15,16,17,18,19,20,21,24,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f'./csv_files/{x}')
C:\Users\rbors\AppData\Local\Temp\ipykernel_18736\4233950251.py:4: DtypeWarning: Columns (1,2,3,4,7,8,9,10,11,12,13,15,16,17,18,19,20,21,24,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f'./csv_files/{x}')
C:\Users\rbors\AppData\Local\Temp\ipykernel_18736\4233950251.py:4: DtypeWarning: Columns (10,11,12,13,15,16,17,18,19,20,21,24,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f'./csv_files/{x}')
C:\Users\rbors\AppData\Local\Temp\ipykernel_18736\4233950251.py:4: DtypeWarning: Columns (10,11,12,13,15,16,17,18,19,20,21,24,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f'./csv_files/{x}')
C:\Users\rbors\AppData\Local\Temp\ipykernel_18736\4233950251.py:4: DtypeWarning: Columns (10,11,12,13,15,16,17,18,19,20,21,24,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f'./csv_files/{x}')
C:\Users\rbors\AppData\Local\Temp\ipykernel_18736\4233950251.py:4: DtypeWarning: Columns (10,11,12,13,15,16,17,18,19,20,21,24,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f'./csv_files/{x}')

In [13]:
df = pd.concat(dfs, ignore_index=True)
df.to_csv('data.csv')

In [14]:
df_chunk = pd.read_csv("data.csv")

C:\Users\rbors\AppData\Local\Temp\ipykernel_18736\2351700596.py:1: DtypeWarning: Columns (2,11,12,14,15,16,17,19,20,21,22,23,24,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df_chunk = pd.read_csv("data.csv")

In [15]:
df_chunk

,Unnamed: 0.1,Unnamed: 0,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,...,Policing operation,Gender,Age range,Self-defined ethnicity,Officer-defined ethnicity,Legislation,Object of search,Outcome,Outcome linked to object of search,Removal of more than just outer clothing
0,0,0,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,0.145949,51.593914,On or near Providence Place,E01000027,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,0.140192,51.582311,On or near Hatch Grove,E01000027,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,0.134947,51.588063,On or near Mead Grove,E01000027,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,3,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,0.134947,51.588063,On or near Mead Grove,E01000027,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,4,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,0.134947,51.588063,On or near Mead Grove,E01000027,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23606654,23606654,191970,827178f4c74110dc649c5ac8136653139a58c10f78090d...,2024-01,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No Location,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23606655,23606655,191971,b92bceced18cc53c5fcb377f0b154e7b69b96b484c7648...,2024-01,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No Location,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23606656,23606656,191972,acd9c90a29c22c3e4a53f1765662e4d718cb397af451c1...,2024-01,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No Location,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23606657,23606657,191973,0a978c195f0daadccaf473f131f50f663f4340618ea802...,2024-01,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No Location,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23606658,23606658,191974,8ddefd590ca561e28874692b8ec02db292d208439336a4...,2024-01,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No Location,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN